from typing import Dict, List, Optional, Protocol, Tuple, runtime_checkable
from uuid import UUID

from src.core.entities.assignment import Assignment


@runtime_checkable
class IAssignmentRepository(Protocol):
    async def get(self, id: UUID) -> Optional[Assignment]: ...

    async def list(self) -> List[Assignment]: ...

    async def list_by_user(self, user_id: UUID) -> List[Assignment]: ...

    async def list_by_event(self, event_id: UUID) -> List[Assignment]: ...

    async def list_paginated(
        self, *, page: int = 1, page_size: int = 20, **filters
    ) -> Tuple[List[Assignment], int]: ...

    async def get_by_event_and_user(self, event_id: UUID, user_id: UUID) -> Optional[Assignment]: ...

    async def count_by_event(self, event_id: UUID) -> int: ...

    async def count_by_user(self, user_id: UUID) -> int: ...

    async def get_upcoming_for_user(self, user_id: UUID) -> List[Assignment]: ...

    async def enrich_assignment(self, assignment: Assignment) -> Dict: ...

    async def create(self, entity: Assignment) -> Assignment: ...

    async def update(self, id: UUID, entity: Assignment) -> Assignment: ...

    async def delete(self, id: UUID) -> bool: ...

    async def delete_by_event(self, event_id: UUID) -> int: ...
