from typing import List, Optional, Protocol, runtime_checkable
from uuid import UUID

from src.core.entities.council_meeting import CouncilMeeting


@runtime_checkable
class ICouncilMeetingRepository(Protocol):
    async def create_meeting(self, meeting: CouncilMeeting) -> CouncilMeeting: ...
    async def get_meeting(self, meeting_id: UUID) -> Optional[CouncilMeeting]: ...
    async def add_attendance(self, meeting_id: UUID, user_id: UUID, **kwargs) -> object: ...
    async def get_responsable_attendances(self, user_id: UUID) -> List: ...
