from typing import List, Optional, Protocol, Tuple, runtime_checkable
from uuid import UUID

from src.core.entities.council_meeting import CouncilMeeting


@runtime_checkable
class ICouncilMeetingRepository(Protocol):
    async def create_meeting(self, meeting: CouncilMeeting) -> CouncilMeeting: ...

    async def get_meeting(self, meeting_id: UUID) -> Optional[CouncilMeeting]: ...

    async def add_attendance(self, meeting_id: UUID, user_id: UUID, **kwargs) -> object: ...

    async def get_responsable_attendances(self, user_id: UUID) -> List: ...

    async def list_meetings(self, page: int, page_size: int) -> Tuple[List[CouncilMeeting], int]: ...

    async def list_attendances(self, meeting_id: UUID) -> List: ...
