from typing import Dict, List, Optional, Protocol, Tuple, runtime_checkable
from uuid import UUID

from src.core.entities.event import Event


@runtime_checkable
class IEventRepository(Protocol):
    async def get(self, id: UUID) -> Optional[Event]: ...
    async def list(self, *, skip: int = 0, limit: int = 50, **filters) -> List[Event]: ...
    async def list_paginated(self, *, page: int = 1, page_size: int = 20, **filters) -> Tuple[List[Event], int]: ...
    async def create(self, entity: Event) -> Event: ...
    async def update(self, id: UUID, entity: Event) -> Event: ...
    async def delete(self, id: UUID) -> bool: ...
    async def get_participant_count(self, event_id: UUID) -> int: ...
    async def get_participants(self, event_id: UUID) -> List[Dict]: ...
    async def add_participant(self, event_id: UUID, user_id: UUID, **kwargs) -> object: ...
    async def get_events_for_user(self, user_id: UUID) -> List[Event]: ...
