from typing import Dict, List, Optional, Protocol, Tuple, runtime_checkable
from uuid import UUID

from src.core.entities.financial_entry import Discrepancy, FinancialEntry


@runtime_checkable
class IFinancialEntryRepository(Protocol):
    async def create(self, entry: FinancialEntry) -> FinancialEntry: ...

    async def get_by_id(self, entry_id: UUID) -> Optional[FinancialEntry]: ...

    async def list_entries(
        self, *, page: int = 1, page_size: int = 20, **filters
    ) -> Tuple[List[FinancialEntry], int]: ...

    async def update(self, entry: FinancialEntry) -> FinancialEntry: ...

    async def delete(self, entry_id: UUID) -> bool: ...

    async def verify(self, entry_id: UUID, verified_by: UUID) -> Optional[FinancialEntry]: ...

    async def get_statistics(self, **filters) -> Dict: ...

    async def get_summary_by_category(self, **filters) -> List[Dict]: ...


@runtime_checkable
class IDiscrepancyRepository(Protocol):
    async def create(self, discrepancy: Discrepancy) -> Discrepancy: ...

    async def get_by_id(self, discrepancy_id: UUID) -> Optional[Discrepancy]: ...

    async def get_by_entry(self, entry_id: UUID) -> List[Discrepancy]: ...

    async def list_unresolved(self) -> List[Discrepancy]: ...

    async def resolve(self, discrepancy_id: UUID, resolved_by: UUID) -> Optional[Discrepancy]: ...

    async def delete(self, discrepancy_id: UUID) -> bool: ...
