from typing import List, Optional, Protocol, runtime_checkable
from uuid import UUID

from src.core.entities.invitation import InvitationCode, InvitationStatus


@runtime_checkable
class IInvitationRepository(Protocol):
    async def create(self, invitation_code: InvitationCode) -> InvitationCode: ...

    async def get_by_code(self, code: str) -> Optional[InvitationCode]: ...

    async def get_by_id(self, invitation_id: UUID) -> Optional[InvitationCode]: ...

    async def get_all_by_admin(self, admin_id: UUID) -> List[InvitationCode]: ...

    async def update(self, invitation_id: UUID, **kwargs) -> Optional[InvitationCode]: ...

    async def mark_as_used(self, code: str, used_by_id: UUID) -> Optional[InvitationCode]: ...

    async def revoke(self, invitation_id: UUID) -> Optional[InvitationCode]: ...

    async def is_valid(self, code: str) -> bool: ...

    async def get_by_email(self, email: str) -> Optional[InvitationCode]: ...
