from typing import Dict, List, Optional, Protocol, Tuple, runtime_checkable
from uuid import UUID

from src.core.entities.material import AubeTask, CleaningTask, MaintenanceHistory, MaterialItem, TaskAssignment


@runtime_checkable
class IMaterialItemRepository(Protocol):
    async def create(self, item: MaterialItem) -> MaterialItem: ...
    async def get_by_id(self, item_id: UUID) -> Optional[MaterialItem]: ...
    async def list_items(self, *, page: int = 1, page_size: int = 20, **filters) -> Tuple[List[MaterialItem], int]: ...
    async def update(self, item: MaterialItem) -> MaterialItem: ...
    async def delete(self, item_id: UUID) -> bool: ...
    async def get_items_needing_maintenance(self) -> List[MaterialItem]: ...


@runtime_checkable
class ICleaningTaskRepository(Protocol):
    async def create(self, task: CleaningTask) -> CleaningTask: ...
    async def get_by_id(self, task_id: UUID) -> Optional[CleaningTask]: ...
    async def list_tasks(self, *, page: int = 1, page_size: int = 20, **filters) -> Tuple[List[CleaningTask], int]: ...
    async def update(self, task: CleaningTask) -> CleaningTask: ...
    async def delete(self, task_id: UUID) -> bool: ...


@runtime_checkable
class ITaskAssignmentRepository(Protocol):
    async def create(self, assignment: TaskAssignment) -> TaskAssignment: ...
    async def create_batch(self, assignments: List[TaskAssignment]) -> List[TaskAssignment]: ...
    async def get_by_task(self, task_id: UUID) -> List[TaskAssignment]: ...
    async def get_by_servant(self, servant_id: UUID, **filters) -> List[TaskAssignment]: ...
    async def delete(self, assignment_id: UUID) -> bool: ...


@runtime_checkable
class IAubeTaskRepository(Protocol):
    async def create(self, task: AubeTask) -> AubeTask: ...
    async def get_by_id(self, task_id: UUID) -> Optional[AubeTask]: ...
    async def list_tasks(self, *, page: int = 1, page_size: int = 20, **filters) -> Tuple[List[AubeTask], int]: ...
    async def update(self, task: AubeTask) -> AubeTask: ...
    async def delete(self, task_id: UUID) -> bool: ...


@runtime_checkable
class IMaintenanceHistoryRepository(Protocol):
    async def create(self, history: MaintenanceHistory) -> MaintenanceHistory: ...
    async def get_by_item(self, item_id: UUID) -> List[MaintenanceHistory]: ...
    async def get_total_cost(self, item_id: UUID) -> float: ...
