from typing import List, Optional, Protocol, Tuple, runtime_checkable
from uuid import UUID

from src.core.entities.report import Report, ReportAttachment


@runtime_checkable
class IReportRepository(Protocol):
    async def create(self, report: Report) -> Report: ...
    async def get_by_id(self, report_id: UUID) -> Optional[Report]: ...
    async def list_reports(self, *, page: int = 1, page_size: int = 20, **filters) -> Tuple[List[Report], int]: ...
    async def update(self, report: Report) -> Report: ...
    async def delete(self, report_id: UUID) -> bool: ...
    async def publish(self, report_id: UUID) -> Optional[Report]: ...
    async def archive(self, report_id: UUID) -> Optional[Report]: ...
    async def get_by_created_by(self, user_id: UUID, *, page: int = 1, page_size: int = 20) -> Tuple[List[Report], int]: ...


@runtime_checkable
class IAttachmentRepository(Protocol):
    async def create(self, attachment: ReportAttachment) -> ReportAttachment: ...
    async def get_by_id(self, attachment_id: UUID) -> Optional[ReportAttachment]: ...
    async def get_by_report(self, report_id: UUID) -> List[ReportAttachment]: ...
    async def delete(self, attachment_id: UUID) -> bool: ...
