from typing import Dict, List, Optional, Protocol, Tuple, runtime_checkable
from uuid import UUID

from src.core.entities.responsable import Nomination, PosteAction


@runtime_checkable
class INominationRepository(Protocol):
    async def get(self, nomination_id: UUID) -> Optional[Nomination]: ...

    async def get_active_by_poste(self, poste: str) -> Optional[Nomination]: ...

    async def get_active_by_user(self, user_id: UUID) -> List[Nomination]: ...

    async def get_active_by_user_and_poste(self, user_id: UUID, poste: str) -> Optional[Nomination]: ...

    async def list_all_active(self) -> List[Nomination]: ...

    async def list_history(self, *, page: int = 1, page_size: int = 20, **filters) -> Tuple[List[Nomination], int]: ...

    async def enrich_nomination(self, nomination: Nomination) -> Dict: ...

    async def create(self, nomination: Nomination) -> Nomination: ...

    async def update(self, nomination: Nomination) -> Nomination: ...


@runtime_checkable
class IPosteActionRepository(Protocol):
    async def get(self, action_id: UUID) -> Optional[PosteAction]: ...

    async def list_by_poste(self, poste: str, **filters) -> List[PosteAction]: ...

    async def list_with_filters(self, **filters) -> Tuple[List[PosteAction], int]: ...

    async def list_by_user(self, user_id: UUID) -> List[PosteAction]: ...

    async def count_by_poste_and_status(self, poste: str, status: str) -> int: ...

    async def enrich_action(self, action: PosteAction) -> Dict: ...

    async def create(self, action: PosteAction) -> PosteAction: ...

    async def update(self, action_id: UUID, **kwargs) -> Optional[PosteAction]: ...

    async def delete(self, action_id: UUID) -> bool: ...
