from typing import Dict, List, Optional, Protocol, Tuple, runtime_checkable
from uuid import UUID

from src.core.entities.sport_culture import (
    EventParticipation,
    EventResult,
    EventTeam,
    SportCultureEvent,
)


@runtime_checkable
class ISportCultureEventRepository(Protocol):
    async def create(self, event: SportCultureEvent) -> SportCultureEvent: ...

    async def get_by_id(self, event_id: UUID) -> Optional[SportCultureEvent]: ...

    async def list_events(
        self, *, page: int = 1, page_size: int = 20, **filters
    ) -> Tuple[List[SportCultureEvent], int]: ...

    async def update(self, event: SportCultureEvent) -> SportCultureEvent: ...

    async def delete(self, event_id: UUID) -> bool: ...

    async def get_upcoming_events(self, limit: int = 10) -> List[SportCultureEvent]: ...


@runtime_checkable
class IEventParticipationRepository(Protocol):
    async def create(self, participation: EventParticipation) -> EventParticipation: ...

    async def create_batch(self, participations: List[EventParticipation]) -> List[EventParticipation]: ...

    async def get_by_id(self, participation_id: UUID) -> Optional[EventParticipation]: ...

    async def get_by_event(self, event_id: UUID) -> List[EventParticipation]: ...

    async def get_by_servant(self, servant_id: UUID, **filters) -> List[EventParticipation]: ...

    async def get_by_event_and_servant(self, event_id: UUID, servant_id: UUID) -> Optional[EventParticipation]: ...

    async def update(self, participation_id: UUID, **kwargs) -> Optional[EventParticipation]: ...

    async def delete(self, participation_id: UUID) -> bool: ...

    async def count_by_event(self, event_id: UUID) -> int: ...

    async def count_confirmed_by_event(self, event_id: UUID) -> int: ...

    async def enrich_participation(self, participation: EventParticipation) -> Dict: ...


@runtime_checkable
class IEventResultRepository(Protocol):
    async def create(self, result: EventResult) -> EventResult: ...

    async def get_by_event(self, event_id: UUID) -> List[EventResult]: ...

    async def delete(self, result_id: UUID) -> bool: ...


@runtime_checkable
class IEventTeamRepository(Protocol):
    async def create(self, team: EventTeam) -> EventTeam: ...

    async def get_by_id(self, team_id: UUID) -> Optional[EventTeam]: ...

    async def get_by_event(self, event_id: UUID) -> List[EventTeam]: ...

    async def update(self, team: EventTeam) -> EventTeam: ...

    async def delete(self, team_id: UUID) -> bool: ...
