from typing import Dict, List, Optional, Protocol, runtime_checkable
from uuid import UUID

from src.core.entities.subgroup import SubGroup, SubGroupMember


@runtime_checkable
class ISubGroupRepository(Protocol):
    async def get(self, group_id: UUID) -> Optional[SubGroup]: ...

    async def get_by_name(self, name: str) -> Optional[SubGroup]: ...

    async def list_all(self, active_only: bool = True) -> List[SubGroup]: ...

    async def create(self, group: SubGroup) -> SubGroup: ...

    async def update(self, group: SubGroup) -> SubGroup: ...

    async def delete(self, group_id: UUID) -> bool: ...

    async def get_member_count(self, group_id: UUID) -> int: ...

    async def get_members(self, group_id: UUID) -> List[SubGroupMember]: ...

    async def get_active_membership(self, user_id: UUID) -> Optional[SubGroupMember]: ...

    async def add_member(self, membership: SubGroupMember) -> SubGroupMember: ...

    async def remove_member(self, group_id: UUID, user_id: UUID) -> bool: ...

    async def get_membership(self, group_id: UUID, user_id: UUID) -> Optional[SubGroupMember]: ...

    async def enrich_member(self, member: SubGroupMember) -> Dict: ...
