from typing import Dict, List, Optional, Protocol, Tuple, runtime_checkable
from uuid import UUID

from src.core.entities.sunday_schedule import (
    SundayMassAssignment,
    SundayMassSlot,
    SundayScheduleTemplate,
)


@runtime_checkable
class ISundayScheduleRepository(Protocol):
    async def create_template(self, template: SundayScheduleTemplate) -> SundayScheduleTemplate: ...

    async def get_template(self, template_id: UUID) -> Optional[SundayScheduleTemplate]: ...

    async def update_template(self, template_id: UUID, **kwargs) -> Optional[SundayScheduleTemplate]: ...

    async def delete_template(self, template_id: UUID) -> bool: ...

    async def list_templates(
        self, *, page: int = 1, page_size: int = 20, **filters
    ) -> Tuple[List[SundayScheduleTemplate], int]: ...

    async def get_published_templates(self) -> List[SundayScheduleTemplate]: ...

    async def create_mass(self, mass: SundayMassSlot) -> SundayMassSlot: ...

    async def get_mass(self, mass_id: UUID) -> Optional[SundayMassSlot]: ...

    async def update_mass(self, mass_id: UUID, **kwargs) -> Optional[SundayMassSlot]: ...

    async def delete_mass(self, mass_id: UUID) -> bool: ...

    async def get_template_masses(self, template_id: UUID) -> List[SundayMassSlot]: ...

    async def create_assignment(self, assignment: SundayMassAssignment) -> SundayMassAssignment: ...

    async def get_assignment(self, assignment_id: UUID) -> Optional[SundayMassAssignment]: ...

    async def get_mass_assignments(self, mass_id: UUID) -> List[SundayMassAssignment]: ...

    async def delete_assignment(self, assignment_id: UUID) -> bool: ...

    async def enrich_template(self, template: SundayScheduleTemplate) -> Dict: ...

    async def enrich_mass(self, mass: SundayMassSlot) -> Dict: ...

    async def enrich_assignment(self, assignment: SundayMassAssignment) -> Dict: ...

    async def get_template_summary(self, template_id: UUID) -> Dict: ...
