from datetime import datetime
from typing import Dict, List, Optional, Protocol, Tuple, runtime_checkable
from uuid import UUID

from src.core.entities.training import (
    SessionMaterial,
    TrainingMaterial,
    TrainingParticipation,
    TrainingSession,
    TrainingStats,
)


@runtime_checkable
class ITrainingSessionRepository(Protocol):
    async def create(self, training_session: TrainingSession) -> TrainingSession: ...
    async def get_by_id(self, session_id: UUID) -> Optional[TrainingSession]: ...
    async def list_sessions(
        self, skip: int = 0, limit: int = 50, **filters
    ) -> Tuple[List[TrainingSession], int]: ...
    async def update(self, session_id: UUID, **kwargs) -> Optional[TrainingSession]: ...
    async def delete(self, session_id: UUID) -> bool: ...
    async def enrich_session(self, session: TrainingSession) -> Dict: ...


@runtime_checkable
class ITrainingParticipationRepository(Protocol):
    async def create(self, participation: TrainingParticipation) -> TrainingParticipation: ...
    async def create_batch(self, participations: List[TrainingParticipation]) -> List[TrainingParticipation]: ...
    async def get_by_id(self, participation_id: UUID) -> Optional[TrainingParticipation]: ...
    async def get_by_session_and_servant(self, session_id: UUID, servant_id: UUID) -> Optional[TrainingParticipation]: ...
    async def list_by_session(self, session_id: UUID) -> List[TrainingParticipation]: ...
    async def list_by_servant(self, servant_id: UUID, **filters) -> List[TrainingParticipation]: ...
    async def update(self, participation_id: UUID, **kwargs) -> Optional[TrainingParticipation]: ...
    async def delete(self, participation_id: UUID) -> bool: ...
    async def get_servant_stats(self, servant_id: UUID) -> TrainingStats: ...


@runtime_checkable
class ITrainingMaterialRepository(Protocol):
    async def create(self, material: TrainingMaterial) -> TrainingMaterial: ...
    async def get_by_id(self, material_id: UUID) -> Optional[TrainingMaterial]: ...
    async def list_materials(self, **filters) -> Tuple[List[TrainingMaterial], int]: ...
    async def update(self, material: TrainingMaterial) -> TrainingMaterial: ...
    async def delete(self, material_id: UUID) -> bool: ...
    async def increment_view_count(self, material_id: UUID) -> bool: ...


@runtime_checkable
class ISessionMaterialRepository(Protocol):
    async def create(self, session_material: SessionMaterial) -> SessionMaterial: ...
    async def get_by_session(self, session_id: UUID) -> List[SessionMaterial]: ...
    async def delete(self, session_material_id: UUID) -> bool: ...
